### PR TITLE
Tooltips with D3

### LINKED ISSUE #5: Add tooltips to chords
Similar to http://bl.ocks.org/nbremer/864b11eb83aac3a1f6a2

Use Bootstrap Popover, show source, destination, amount.

### PR DESCRIPTION
**Pull request by curran**
Will close #5

### CODE REVIEW

**Comment by curran** [comment]
How it looks now 
image

**Comment by ronakmshah** [comment]
Can we add a heading:
"Total packets:" in tooltip on top of whats shown ?

**Comment by curran** [comment]
We could, but the meaning of the numbers depend on what the user has selected, which may be "Count", or may be "Sum of Packets", or some other aggregation. We can hard code this for now if you'd like to make the assumption that "Total packets" will be the aggregation,

**Comment by ronakmshah** [comment]
Oh thats so true.  We can hard code it for now in that case. Thanks.

**Comment by curran** [comment]
Here's what it looks like now:

image

**Comment by ronakmshah** [comment]
Great... Perfect. Thanks

**Pull request merged**
