### PR TITLE
Table Header

### PR DESCRIPTION
**Pull request by curran**
Will close **Add table header** #55

### CODE REVIEW

**Comment by curran** [comment]
Header is there, needs styling.
image

**Comment by curran** [comment]
Here's how it looks after styling:

image

**Comment by ronakmshah** [comment]
Flow**s** between

**Comment by curran** [comment]
Ah yes! Thanks @ronakmshah , will make that change.

I noticed you had different table columns. Would you mind sending a PR with your changes, or letting me know which columns you'd like to have in the table? Thanks!

**Comment by curran** [comment]
How it looks now:

image

**Pull request merged**
